import os
from pdf2image import convert_from_path, convert_from_bytes
from pdf2image.exceptions import (
    PDFInfoNotInstalledError,
    PDFPageCountError,
    PDFSyntaxError,
    PDFPopplerTimeoutError # Added this one, removed PDFTooManyPagesError
)

def convert_pdf_to_png(pdf_input, output_folder, output_filename_prefix='page'):
    """
    Converts a PDF (from path or bytes) to a series of PNG images, one per page.

    Args:
        pdf_input (str or bytes): Path to the PDF file or PDF content as bytes.
        output_folder (str): Folder where PNG images will be saved.
        output_filename_prefix (str, optional): Prefix for the output PNG filenames.
                                               Images will be named <prefix>_1.png, <prefix>_2.png, etc.
                                               Defaults to 'page'.

    Returns:
        list: A list of paths to the generated PNG files. Returns empty list on error.

    Raises:
        FileNotFoundError: If pdf_input is a path and the file is not found.
        PDFInfoNotInstalledError: If poppler is not installed or not in PATH.
        # Other pdf2image specific exceptions can also be raised.
    """
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    generated_images = []

    try:
        if isinstance(pdf_input, str):  # Input is a path
            if not os.path.exists(pdf_input):
                raise FileNotFoundError(f"PDF file not found at: {pdf_input}")
            # convert_from_path with output_folder and output_file returns a list of PIL Image objects,
            # but it *also* saves them. We need to construct the paths.
            # For more control, we can save manually.

            # Let's save manually for explicit path construction
            images = convert_from_path(pdf_input, dpi=200, thread_count=4)
            for i, image in enumerate(images):
                fname = f"{output_filename_prefix}_{i + 1}.png"
                image_path = os.path.join(output_folder, fname)
                image.save(image_path, 'PNG')
                generated_images.append(image_path)

        elif isinstance(pdf_input, bytes): # Input is bytes
            # Similar to above, let's save manually from bytes
            images = convert_from_bytes(pdf_input, dpi=200, thread_count=4)
            for i, image in enumerate(images):
                fname = f"{output_filename_prefix}_{i + 1}.png"
                image_path = os.path.join(output_folder, fname)
                image.save(image_path, 'PNG')
                generated_images.append(image_path)
        else:
            raise ValueError("pdf_input must be a file path (str) or bytes.")

        return generated_images

    except (PDFInfoNotInstalledError, PDFPageCountError, PDFSyntaxError, PDFPopplerTimeoutError) as e: # Updated caught exceptions
        print(f"PDF conversion error: {e}")
        # Consider re-raising or handling more gracefully depending on application needs
        raise  # Re-raise for now so tests can catch it
    except Exception as e:
        print(f"An unexpected error occurred during PDF to PNG conversion: {e}")
        raise # Re-raise

if __name__ == '__main__':
    # For direct testing of this module, you'd need a sample PDF.
    # Let's assume we have a 'sample.pdf' in the project root for testing.
    # In a real test scenario, we'd use a PDF generated by our other modules.

    print("Attempting to convert a sample PDF (if 'sample.pdf' exists)...")
    # Create a dummy sample.pdf if it doesn't exist for basic execution
    # This part is more for ensuring the script runs than a real test
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    sample_pdf_path = os.path.join(project_root, "financial_document_generator", "sample_dummy.pdf")
    test_output_images_folder = os.path.join(project_root, "financial_document_generator", "test_converted_images")

    # Create a simple dummy PDF with WeasyPrint for testing if no sample exists
    try:
        from weasyprint import HTML as WeasyHTML
        if not os.path.exists(sample_pdf_path):
            dummy_html = "<html><body><h1>Test PDF</h1><p>This is a test.</p></body></html>"
            WeasyHTML(string=dummy_html).write_pdf(sample_pdf_path)
            print(f"Created dummy PDF: {sample_pdf_path}")
    except ImportError:
        print("WeasyPrint not available to create dummy PDF for testing converters.py directly.")
    except Exception as e:
        print(f"Error creating dummy PDF: {e}")


    if os.path.exists(sample_pdf_path):
        try:
            print(f"Using PDF: {sample_pdf_path}")
            print(f"Outputting PNGs to: {test_output_images_folder}")

            # Test with PDF path
            png_files_from_path = convert_pdf_to_png(sample_pdf_path, test_output_images_folder, "path_test")
            if png_files_from_path:
                print(f"Successfully converted (from path) to PNG: {png_files_from_path}")
            else:
                print("Conversion from path failed or produced no files.")

            # Test with PDF bytes
            with open(sample_pdf_path, 'rb') as f:
                pdf_bytes = f.read()
            png_files_from_bytes = convert_pdf_to_png(pdf_bytes, test_output_images_folder, "bytes_test")
            if png_files_from_bytes:
                print(f"Successfully converted (from bytes) to PNG: {png_files_from_bytes}")
            else:
                print("Conversion from bytes failed or produced no files.")

        except PDFInfoNotInstalledError:
            print("CONVERTER TEST ERROR: Poppler is not installed or not in PATH. PDF to PNG conversion will fail.")
            print("Please install Poppler utilities (e.g., 'sudo apt-get install poppler-utils' on Debian/Ubuntu or 'brew install poppler' on macOS).")
        except Exception as e:
            print(f"Error during __main__ test of converters.py: {e}")
    else:
        print(f"Sample PDF '{sample_pdf_path}' not found. Skipping direct test of convert_pdf_to_png.")
